import {
  app,
  BrowserWindow,
  Tray,
  Menu,
  MenuItemConstructorOptions,
  dialog,
  MenuItem,
} from "electron";
import { promisify } from "util";
import { exec } from "child_process";
const asyncExec = promisify(exec);

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
  });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.webContents.openDevTools();
};

let trayIcon: Tray;
let currentConnection: string | null = null;

const connect = async (menuItem: MenuItem) => {
  console.log(`Attempted connection to ${menuItem.id}`);
  currentConnection = menuItem.id;

  const contextMenu = await buildContextMenu();

  trayIcon.setContextMenu(contextMenu);
};

const disconnect = async (menuItem: MenuItem) => {
  console.log(`Attempted disconnect from ${menuItem.id}`);
  currentConnection = null;

  const contextMenu = await buildContextMenu();

  trayIcon.setContextMenu(contextMenu);
}

const buildContextMenu = async (): Promise<Menu> => {
  //TODO: Should we be using USER or USERNAME?
  const configs = await asyncExec(
    'openvpn3 configs-list | grep ${USER} | sed "s/${USER}$//; s/[ \t]*$//"'
  );

  const parsedConfigNames = configs.stdout.split("\n").filter(Boolean);

  const configMenuItems = parsedConfigNames.map<MenuItemConstructorOptions>(
    (configName) => {
      const isCurrentConnection = currentConnection === configName;
      return {
        id: configName,
        type: "checkbox",
        checked: isCurrentConnection,
        label: `${
          isCurrentConnection ? "Disconnect from" : "Connect to"
        } ${configName}`,
        enabled: !currentConnection || isCurrentConnection,
        click: isCurrentConnection ? disconnect : connect,
      };
    }
  );

  return Menu.buildFromTemplate([
    { type: "separator" },
    ...configMenuItems,
    { type: "separator" },
    { label: "Quit", role: "quit" },
  ]);
};

const createTray = async (): Promise<void> => {
  trayIcon = new Tray("src/assets/icon.png");

  const contextMenu = await buildContextMenu();

  trayIcon.setContextMenu(contextMenu);

  trayIcon.on("click", () => {
    dialog.showMessageBox({ message: "teste", title: "teste" });
  });
};

app.on("ready", createTray);
